package com.iven.app.utils;

import com.iven.app.bean.CompanyBean;

import java.util.ArrayList;

/**
 * @author Iven
 * @date 2017/3/4 23:09
 * 常量
 */

public class Constant {
    public static final String SUGGESTION_FLAG = "suggestion_flag";
    public static final String HEWEATHER_KEY = "c8223f0591db43d9a425de5556ece9ce";
    public static final String NEWS_ID = "news_id";
    public static final String NEWS_POST_ID = "news_post_id";
    public static final String NEWS_IMG_RES = "news_img_res";
    public static final int RESULT_CODE = 1009;
    public static final String FLAG_COMPANY = "company";


    public static  ArrayList<CompanyBean> getWLINfo() {
        ArrayList<CompanyBean> list = new ArrayList<>();
        String name = WULIU.replace("{", "").replace("}", "").replace("\n", "").replace(" ", "");
        String[] split = name.split(",");
        for (int i = 0; i < split.length; i++) {
            String replace = split[i].replace("\"", "");
            CompanyBean CompanyBean = new CompanyBean();
            CompanyBean.setName(replace.substring(0, replace.indexOf(":")));
            CompanyBean.setCode(replace.substring(replace.indexOf(":") + 1, replace.length()));
            list.add(CompanyBean);
        }
        return list;
    }


    public static final String WULIU = "{\n" +
            "  \"AOL澳通速递\": \"aolau\",\n" +
            "  \"A2U速递\": \"a2u\",\n" +
            "  \"AAE快递\": \"aae\",\n" +
            "  \"安能物流\": \"annengwuliu\",\n" +
            "  \"安迅物流\": \"anxl\",\n" +
            "  \"澳邮中国快运\": \"auexpress\",\n" +
            "  \"安鲜达\": \"exfresh\",\n" +
            "  \"安捷物流\": \"anjie88\",\n" +
            "  \"BCWELT\": \"bcwelt\",\n" +
            "  \"百世快运\": \"baishiwuliu\",\n" +
            "  \"百世快递\": \"huitongkuaidi\",\n" +
            "  \"包裹/平邮/挂号信\": \"youzhengguonei\",\n" +
            "  \"百福东方物流\": \"baifudongfang\",\n" +
            "  \"邦送物流\": \"bangsongwuliu\",\n" +
            "  \"北青小红帽\": \"xiaohongmao\",\n" +
            "  \"宝凯物流\": \"lbbk\",\n" +
            "  \"百千诚物流\": \"bqcwl\",\n" +
            "  \"博源恒通\": \"byht\",\n" +
            "  \"百成大达物流\": \"idada\",\n" +
            "  \"百腾物流\": \"baitengwuliu\",\n" +
            "  \"巴伦支快递\": \"balunzhi\",\n" +
            "  \"笨鸟海淘\": \"birdex\",\n" +
            "  \"百事亨通\": \"bsht\",\n" +
            "  \"奔腾物流\": \"benteng\",\n" +
            "  \"布谷鸟速递\": \"cuckooexpess\",\n" +
            "  \"邦工快运\": \"bgky100\",\n" +
            "  \"堡昕德速递\": \"bosind\",\n" +
            "  \"斑马物联网\": \"banma\",\n" +
            "  \"CE易欧通国际速递\": \"cloudexpress\",\n" +
            "  \"COE（东方快递）\": \"coe\",\n" +
            "  \"城市100\": \"city100\",\n" +
            "  \"城际速递\": \"chengjisudi\",\n" +
            "  \"成都立即送\": \"lijisong\",\n" +
            "  \"出口易\": \"chukou1\",\n" +
            "  \"晟邦物流\": \"nanjingshengbang\",\n" +
            "  \"程光快递\": \"flyway\",\n" +
            "  \"传喜物流\": \"chuanxiwuliu\",\n" +
            "  \"钏博物流\": \"cbo56\",\n" +
            "  \"城铁物流\": \"cex\",\n" +
            "  \"DHL中国\": \"dhl\",\n" +
            "  \"DHL国际\": \"dhlen\",\n" +
            "  \"DHL德国\": \"dhlde\",\n" +
            "  \"德邦\": \"debangwuliu\",\n" +
            "  \"大田物流\": \"datianwuliu\",\n" +
            "  \"东方快递\": \"coe\",\n" +
            "  \"递四方\": \"disifang\",\n" +
            "  \"大洋物流\": \"dayangwuliu\",\n" +
            "  \"店通快递\": \"diantongkuaidi\",\n" +
            "  \"德创物流\": \"dechuangwuliu\",\n" +
            "  \"东红物流\": \"donghong\",\n" +
            "  \"D速物流\": \"dsukuaidi\",\n" +
            "  \"东瀚物流\": \"donghanwl\",\n" +
            "  \"达方物流\": \"dfpost\",\n" +
            "  \"东骏快捷物流\": \"dongjun\",\n" +
            "  \"叮咚澳洲转运\": \"dindon\",\n" +
            "  \"大众佐川急便\": \"dazhong\",\n" +
            "  \"德方物流\": \"ahdf\",\n" +
            "  \"德中快递\": \"decnlh\",\n" +
            "  \"德坤供应链\": \"dekuncn\",\n" +
            "  \"达速物流\": \"dasu\",\n" +
            "  \"德豪驿\": \"dehaoyi\",\n" +
            "  \"DHL Paket\": \"dhlpaket\",\n" +
            "  \"德国优拜物流\": \"ubuy\",\n" +
            "  \"德国雄鹰速递\": \"adlerlogi\",\n" +
            "  \"德国云快递\": \"yunexpress\",\n" +
            "  \"EU-EXPRESS\": \"euexpress\",\n" +
            "  \"EMS快递查询\": \"ems\",\n" +
            "  \"EMS国际快递查询\": \"emsguoji\",\n" +
            "  \"俄顺达\": \"eshunda\",\n" +
            "  \"EWE全球快递\": \"ewe\",\n" +
            "  \"FedEx快递查询\": \"fedex\",\n" +
            "  \"FedEx美国\": \"fedexus\",\n" +
            "  \"FedEx英国\": \"fedexuk\",\n" +
            "  \"FOX国际速递\": \"fox\",\n" +
            "  \"凡客如风达\": \"rufengda\",\n" +
            "  \"飞康达物流\": \"feikangda\",\n" +
            "  \"飞豹快递\": \"feibaokuaidi\",\n" +
            "  \"飞狐快递\": \"feihukuaidi\",\n" +
            "  \"凡宇速递\": \"fanyukuaidi\",\n" +
            "  \"颿达国际快递\": \"fandaguoji\",\n" +
            "  \"飞远配送\": \"feiyuanvipshop\",\n" +
            "  \"飞鹰物流\": \"hnfy\",\n" +
            "  \"风行天下\": \"fengxingtianxia\",\n" +
            "  \"飞力士物流\": \"flysman\",\n" +
            "  \"飞邦快递\": \"fbkd\",\n" +
            "  \"丰程物流\": \"sccod\",\n" +
            "  \"泛远国际物流\": \"farlogistis\",\n" +
            "  \"疯狂快递\": \"crazyexpress\",\n" +
            "  \"法翔速运\": \"ftlexpress\",\n" +
            "  \"富腾达快递\": \"ftd\",\n" +
            "  \"GLS\": \"gls\",\n" +
            "  \"GSM\": \"gsm\",\n" +
            "  \"GATI快递\": \"gaticn\",\n" +
            "  \"GTS快递\": \"gts\",\n" +
            "  \"挂号信/国内邮件\": \"youzhengguonei\",\n" +
            "  \"国通快递\": \"guotongkuaidi\",\n" +
            "  \"国际邮件查询\": \"youzhengguoji\",\n" +
            "  \"港中能达物流\": \"ganzhongnengda\",\n" +
            "  \"港快速递\": \"gdkd\",\n" +
            "  \"共速达\": \"gongsuda\",\n" +
            "  \"广通速递（山东）\": \"gtongsudi\",\n" +
            "  \"高铁速递\": \"hre\",\n" +
            "  \"冠达快递\": \"gda\",\n" +
            "  \"哥士传奇速递\": \"gscq365\",\n" +
            "  \"冠捷物流\": \"gjwl\",\n" +
            "  \"国晶物流\": \"xdshipping\",\n" +
            "  \"华宇物流\": \"tiandihuayu\",\n" +
            "  \"恒路物流\": \"hengluwuliu\",\n" +
            "  \"好来运快递\": \"hlyex\",\n" +
            "  \"华夏龙物流\": \"huaxialongwuliu\",\n" +
            "  \"海航天天\": \"tiantian\",\n" +
            "  \"河北建华\": \"hebeijianhua\",\n" +
            "  \"海盟速递\": \"haimengsudi\",\n" +
            "  \"华企快运\": \"huaqikuaiyun\",\n" +
            "  \"昊盛物流\": \"haoshengwuliu\",\n" +
            "  \"户通物流\": \"hutongwuliu\",\n" +
            "  \"华航快递\": \"hzpl\",\n" +
            "  \"黄马甲快递\": \"huangmajia\",\n" +
            "  \"合众速递（UCS）\": \"ucs\",\n" +
            "  \"皇家物流\": \"pfcexpress\",\n" +
            "  \"伙伴物流\": \"huoban\",\n" +
            "  \"红马速递\": \"nedahm\",\n" +
            "  \"汇文配送\": \"huiwen\",\n" +
            "  \"华赫物流\": \"nmhuahe\",\n" +
            "  \"猴急送\": \"hjs\",\n" +
            "  \"航宇快递\": \"hangyu\",\n" +
            "  \"辉联物流\": \"huilian\",\n" +
            "  \"环球速运\": \"huanqiu\",\n" +
            "  \"华达快运\": \"huada\",\n" +
            "  \"华通务达物流\": \"htwd\",\n" +
            "  \"海派通\": \"hipito\",\n" +
            "  \"环球通达\": \"hqtd\",\n" +
            "  \"航空快递\": \"airgtc\",\n" +
            "  \"好又快物流\": \"haoyoukuai\",\n" +
            "  \"韩润物流\": \"hanrun\",\n" +
            "  \"河南次晨达\": \"ccd\",\n" +
            "  \"和丰同城\": \"hfwuxi\",\n" +
            "  \"荷兰 Sky Post\": \"skypost\",\n" +
            "  \"鸿讯物流\": \"hongxun\",\n" +
            "  \"宏捷国际物流\": \"hongjie\",\n" +
            "  \"汇通天下物流\": \"httx56\",\n" +
            "  \"恒通快递\": \"lqht\",\n" +
            "  \"黑狗物流\": \"higo\",\n" +
            "  \"恒宇运通\": \"hyytes\",\n" +
            "  \"恒瑞物流\": \"hengrui56\",\n" +
            "  \"环创物流\": \"ghl\",\n" +
            "  \"河南全速通\": \"hnqst\",\n" +
            "  \"佳吉物流\": \"jiajiwuliu\",\n" +
            "  \"佳怡物流\": \"jiayiwuliu\",\n" +
            "  \"加运美快递\": \"jiayunmeiwuliu\",\n" +
            "  \"急先达物流\": \"jixianda\",\n" +
            "  \"京广速递快件\": \"jinguangsudikuaijian\",\n" +
            "  \"晋越快递\": \"jinyuekuaidi\",\n" +
            "  \"京东快递\": \"jd\",\n" +
            "  \"捷特快递\": \"jietekuaidi\",\n" +
            "  \"久易快递\": \"jiuyicn\",\n" +
            "  \"九曳供应链\": \"jiuyescm\",\n" +
            "  \"骏丰国际速递\": \"junfengguoji\",\n" +
            "  \"佳家通\": \"jiajiatong56\",\n" +
            "  \"吉日优派\": \"jrypex\",\n" +
            "  \"锦程国际物流\": \"jinchengwuliu\",\n" +
            "  \"景光物流\": \"jgwl\",\n" +
            "  \"急顺通\": \"pzhjst\",\n" +
            "  \"捷网俄全通\": \"ruexp\",\n" +
            "  \"嘉里大通\": \"jialidatong\",\n" +
            "  \"金马甲\": \"jmjss\",\n" +
            "  \"佳成快递\": \"jiacheng\",\n" +
            "  \"骏绅物流\": \"jsexpress\",\n" +
            "  \"锦程快递\": \"hrex\",\n" +
            "  \"快捷快递\": \"kuaijiesudi\",\n" +
            "  \"康力物流\": \"kangliwuliu\",\n" +
            "  \"跨越速运\": \"kuayue\",\n" +
            "  \"快优达速递\": \"kuaiyouda\",\n" +
            "  \"快淘快递\": \"kuaitao\",\n" +
            "  \"开心快递\": \"happylink\",\n" +
            "  \"联邦快递\": \"lianbangkuaidi\",\n" +
            "  \"联昊通物流\": \"lianhaowuliu\",\n" +
            "  \"龙邦速递\": \"longbanwuliu\",\n" +
            "  \"乐捷递\": \"lejiedi\",\n" +
            "  \"立即送\": \"lijisong\",\n" +
            "  \"蓝弧快递\": \"lanhukuaidi\",\n" +
            "  \"乐天速递\": \"ltexp\",\n" +
            "  \"鲁通快运\": \"lutong\",\n" +
            "  \"乐递供应链\": \"ledii\",\n" +
            "  \"论道国际物流\": \"lundao\",\n" +
            "  \"林安物流\": \"lasy56\",\n" +
            "  \"ME物流\": \"macroexpressco\",\n" +
            "  \"民航快递\": \"minghangkuaidi\",\n" +
            "  \"美国快递\": \"meiguokuaidi\",\n" +
            "  \"门对门\": \"menduimen\",\n" +
            "  \"明亮物流\": \"mingliangwuliu\",\n" +
            "  \"民邦速递\": \"minbangsudi\",\n" +
            "  \"闽盛快递\": \"minshengkuaidi\",\n" +
            "  \"麦力快递\": \"mailikuaidi\",\n" +
            "  \"木春货运\": \"mchy\",\n" +
            "  \"美快国际物流\": \"meiquick\",\n" +
            "  \"美通快递\": \"valueway\",\n" +
            "  \"马珂博逻\": \"cnmcpl\",\n" +
            "  \"能达速递\": \"ganzhongnengda\",\n" +
            "  \"偌亚奥国际\": \"nuoyaao\",\n" +
            "  \"诺尔国际物流\": \"nuoer\",\n" +
            "  \"尼尔快递\": \"nell\",\n" +
            "  \"OCS\": \"ocs\",\n" +
            "  \"欧亚专线\": \"euasia\",\n" +
            "  \"PCA Express\": \"pcaexpress\",\n" +
            "  \"平安达腾飞\": \"pingandatengfei\",\n" +
            "  \"陪行物流\": \"peixingwuliu\",\n" +
            "  \"品骏快递\": \"pjbest\",\n" +
            "  \"鹏远国际速递\": \"pengyuanexpress\",\n" +
            "  \"全峰快递\": \"quanfengkuaidi\",\n" +
            "  \"全一快递\": \"quanyikuaidi\",\n" +
            "  \"全日通快递\": \"quanritongkuaidi\",\n" +
            "  \"全晨快递\": \"quanchenkuaidi\",\n" +
            "  \"7天连锁物流\": \"sevendays\",\n" +
            "  \"秦邦快运\": \"qbexpress\",\n" +
            "  \"全信通快递\": \"quanxintong\",\n" +
            "  \"全速通国际快递\": \"quansutong\",\n" +
            "  \"秦远物流\": \"qinyuan\",\n" +
            "  \"启辰国际物流\": \"qichen\",\n" +
            "  \"全速快运\": \"quansu\",\n" +
            "  \"全之鑫物流\": \"qzx56\",\n" +
            "  \"千顺快递\": \"qskdyxgs\",\n" +
            "  \"全时速运\": \"runhengfeng\",\n" +
            "  \"如风达快递\": \"rufengda\",\n" +
            "  \"日昱物流\": \"riyuwuliu\",\n" +
            "  \"瑞丰速递\": \"rfsd\",\n" +
            "  \"日日顺物流\": \"rrs\",\n" +
            "  \"日益通速递\": \"rytsd\",\n" +
            "  \"瑞达国际速递\": \"ruidaex\",\n" +
            "  \"日日顺快线\": \"rrskx\",\n" +
            "  \"容智物流速运\": \"gdrz58\",\n" +
            "  \"顺丰速运\": \"shunfeng\",\n" +
            "  \"申通快递\": \"shentong\",\n" +
            "  \"速尔快递\": \"suer\",\n" +
            "  \"山东海红\": \"haihongwangsong\",\n" +
            "  \"盛辉物流\": \"shenghuiwuliu\",\n" +
            "  \"世运快递\": \"shiyunkuaidi\",\n" +
            "  \"盛丰物流\": \"shengfengwuliu\",\n" +
            "  \"上大物流\": \"shangda\",\n" +
            "  \"三态速递\": \"santaisudi\",\n" +
            "  \"赛澳递\": \"saiaodi\",\n" +
            "  \"申通E物流\": \"shentong\",\n" +
            "  \"圣安物流\": \"shenganwuliu\",\n" +
            "  \"山西红马甲\": \"sxhongmajia\",\n" +
            "  \"穗佳物流\": \"suijiawuliu\",\n" +
            "  \"沈阳佳惠尔\": \"syjiahuier\",\n" +
            "  \"上海林道货运\": \"shlindao\",\n" +
            "  \"十方通物流\": \"sfift\",\n" +
            "  \"山东广通速递\": \"gtongsudi\",\n" +
            "  \"顺捷丰达\": \"shunjiefengda\",\n" +
            "  \"速必达物流\": \"subida\",\n" +
            "  \"速通成达物流\": \"htwd\",\n" +
            "  \"速腾物流\": \"suteng\",\n" +
            "  \"速方国际物流\": \"bphchina\",\n" +
            "  \"顺通快递\": \"stkd\",\n" +
            "  \"速递中国\": \"sendtochina\",\n" +
            "  \"苏宁快递\": \"suning\",\n" +
            "  \"四海快递\": \"sihaiet\",\n" +
            "  \"首通快运\": \"staky\",\n" +
            "  \"顺时达物流\": \"hnssd56\",\n" +
            "  \"Superb Grace\": \"superb\",\n" +
            "  \"圣飞捷快递\": \"sfjhd\",\n" +
            "  \"上海航瑞货运\": \"hangrui\",\n" +
            "  \"嗖一下同城快递\": \"sofast56\",\n" +
            "  \"天天快递\": \"tiantian\",\n" +
            "  \"TNT快递\": \"tnt\",\n" +
            "  \"天地华宇\": \"tiandihuayu\",\n" +
            "  \"通和天下\": \"tonghetianxia\",\n" +
            "  \"天纵物流\": \"tianzong\",\n" +
            "  \"同舟行物流\": \"chinatzx\",\n" +
            "  \"腾达速递\": \"nntengda\",\n" +
            "  \"泰国138\": \"sd138\",\n" +
            "  \"通达兴物流\": \"tongdaxing\",\n" +
            "  \"天联快运\": \"tlky\",\n" +
            "  \"途鲜物流\": \"ibenben\",\n" +
            "  \"淘韩国际快递\": \"krtao\",\n" +
            "  \"特急送\": \"lntjs\",\n" +
            "  \"UPS快递查询\": \"ups\",\n" +
            "  \"UC优速快递\": \"youshuwuliu\",\n" +
            "  \"UCS（合众速递）\": \"ucs\",\n" +
            "  \"USPS美国邮政\": \"usps\",\n" +
            "  \"UEQ快递\": \"ueq\",\n" +
            "  \"万象物流\": \"wanxiangwuliu\",\n" +
            "  \"微特派\": \"weitepai\",\n" +
            "  \"万家物流\": \"wanjiawuliu\",\n" +
            "  \"万博快递\": \"wanboex\",\n" +
            "  \"万家通\": \"timedg\",\n" +
            "  \"威时沛运\": \"wtdchina\",\n" +
            "  \"微转运\": \"wzhaunyun\",\n" +
            "  \"万通快递\": \"gswtkd\",\n" +
            "  \"渥途国际速运\": \"wotu\",\n" +
            "  \"豌豆物流\": \"wandougongzhu\",\n" +
            "  \"万家康物流\": \"wjkwl\",\n" +
            "  \"希优特快递\": \"xiyoutekuaidi\",\n" +
            "  \"新邦物流\": \"xinbangwuliu\",\n" +
            "  \"信丰物流\": \"xinfengwuliu\",\n" +
            "  \"新蛋物流\": \"neweggozzo\",\n" +
            "  \"祥龙运通物流\": \"xianglongyuntong\",\n" +
            "  \"西安城联速递\": \"xianchengliansudi\",\n" +
            "  \"喜来快递\": \"xilaikd\",\n" +
            "  \"鑫世锐达\": \"xsrd\",\n" +
            "  \"鑫通宝物流\": \"xtb\",\n" +
            "  \"信天捷快递\": \"xintianjie\",\n" +
            "  \"西安胜峰\": \"xaetc\",\n" +
            "  \"新顺丰（NSF）\": \"nsf\",\n" +
            "  \"先锋快递\": \"xianfeng\",\n" +
            "  \"新速航\": \"sunspeedy\",\n" +
            "  \"西邮寄\": \"xipost\",\n" +
            "  \"信联通\": \"sinatone\",\n" +
            "  \"新杰物流\": \"sunjex\",\n" +
            "  \"心怡物流\": \"alog\",\n" +
            "  \"新时速物流\": \"csxss\",\n" +
            "  \"翔腾物流\": \"xiangteng\",\n" +
            "  \"西翼物流\": \"westwing\",\n" +
            "  \"小熊物流\": \"littlebearbear\",\n" +
            "  \"鑫和高铁快运\": \"gaotieex\",\n" +
            "  \"圆通速递\": \"yuantong\",\n" +
            "  \"韵达快递\": \"yunda\",\n" +
            "  \"韵达美国件\": \"yundaexus\",\n" +
            "  \"邮政国内\": \"youzhengguonei\",\n" +
            "  \"邮政国际\": \"youzhengguoji\",\n" +
            "  \"邮政EMS速递\": \"ems\",\n" +
            "  \"运通快递\": \"yuntongkuaidi\",\n" +
            "  \"宇鑫物流\": \"yuxinwuliu\",\n" +
            "  \"远成物流\": \"yuanchengwuliu\",\n" +
            "  \"优速快递\": \"youshuwuliu\",\n" +
            "  \"越丰物流\": \"yuefengwuliu\",\n" +
            "  \"源安达快递\": \"yuananda\",\n" +
            "  \"原飞航物流\": \"yuanfeihangwuliu\",\n" +
            "  \"银捷速递\": \"yinjiesudi\",\n" +
            "  \"一统飞鸿\": \"yitongfeihong\",\n" +
            "  \"亚风速递\": \"yafengsudi\",\n" +
            "  \"易通达\": \"yitongda\",\n" +
            "  \"邮必佳\": \"youbijia\",\n" +
            "  \"一柒物流\": \"yiqiguojiwuliu\",\n" +
            "  \"音素快运\": \"yinsu\",\n" +
            "  \"亿领速运\": \"yilingsuyun\",\n" +
            "  \"煜嘉物流\": \"yujiawuliu\",\n" +
            "  \"英脉物流\": \"gml\",\n" +
            "  \"云豹国际货运\": \"leopard\",\n" +
            "  \"云南中诚\": \"czwlyn\",\n" +
            "  \"优配速运\": \"sdyoupei\",\n" +
            "  \"永昌物流\": \"yongchang\",\n" +
            "  \"御风速运\": \"yufeng\",\n" +
            "  \"亚马逊物流\": \"yamaxunwuliu\",\n" +
            "  \"优速通达\": \"yousutongda\",\n" +
            "  \"亿顺航\": \"yishunhang\",\n" +
            "  \"永旺达快递\": \"yongwangda\",\n" +
            "  \"易客满\": \"ecmscn\",\n" +
            "  \"英超物流\": \"yingchao\",\n" +
            "  \"益递物流\": \"edlogistics\",\n" +
            "  \"远洋国际\": \"yyexpress\",\n" +
            "  \"一号仓\": \"onehcang\",\n" +
            "  \"远成快运\": \"ycgky\",\n" +
            "  \"一号线\": \"lineone\",\n" +
            "  \"壹品速递\": \"ypsd\",\n" +
            "  \"易达通快递\": \"qexpress\",\n" +
            "  \"鹰运国际速递\": \"vipexpress\",\n" +
            "  \"YLTD\": \"el56\",\n" +
            "  \"一运全成物流\": \"yyqc56\",\n" +
            "  \"韵丰物流\": \"yunfeng56\",\n" +
            "  \"驿扬国际速运\": \"iyoungspeed\",\n" +
            "  \"一站通快递\": \"zgyzt\",\n" +
            "  \"易优包裹\": \"eupackage\",\n" +
            "  \"云达通\": \"ydglobe\",\n" +
            "  \"运东西\": \"yundx\",\n" +
            "  \"洋包裹\": \"yangbaoguo\",\n" +
            "  \"优联吉运\": \"uluckex\",\n" +
            "  \"优邦速运\": \"ubonex\",\n" +
            "  \"玥玛速运\": \"yue777\",\n" +
            "  \"远为快递\": \"ywexpress\",\n" +
            "  \"易转运\": \"ezhuanyuan\",\n" +
            "  \"中通快递\": \"zhongtong\",\n" +
            "  \"宅急送\": \"zhaijisong\",\n" +
            "  \"中铁快运\": \"ztky\",\n" +
            "  \"中铁物流\": \"zhongtiewuliu\",\n" +
            "  \"中邮物流\": \"zhongyouwuliu\",\n" +
            "  \"中国东方(COE)\": \"coe\",\n" +
            "  \"芝麻开门\": \"zhimakaimen\",\n" +
            "  \"中国邮政快递\": \"youzhengguonei\",\n" +
            "  \"郑州建华\": \"zhengzhoujianhua\",\n" +
            "  \"中速快件\": \"zhongsukuaidi\",\n" +
            "  \"中天万运\": \"zhongtianwanyun\",\n" +
            "  \"中睿速递\": \"zhongruisudi\",\n" +
            "  \"中外运速递\": \"zhongwaiyun\",\n" +
            "  \"增益速递\": \"zengyisudi\",\n" +
            "  \"郑州速捷\": \"sujievip\",\n" +
            "  \"智通物流\": \"ztong\",\n" +
            "  \"至诚通达快递\": \"zhichengtongda\",\n" +
            "  \"众辉达物流\": \"zhdwl\",\n" +
            "  \"直邮易\": \"kuachangwuliu\",\n" +
            "  \"中运全速\": \"topspeedex\",\n" +
            "  \"中欧快运\": \"otobv\",\n" +
            "  \"准实快运\": \"zsky123\",\n" +
            "  \"中国翼\": \"cnws\",\n" +
            "  \"中宇天地\": \"zytdscm\",\n" +
            "  \"转运四方\": \"zhuanyunsifang\",\n" +
            "  \"卓烨快递\": \"hrbzykd\"\n" +
            "}";
}

